### ISSUE TITLE
Странный шрифт

### ISSUE THREAD

**Issue by sergeyklay** [morsbox/rusrails#131]
Привет

Это не совсем баг, но я хочу обратить ваше внимание.
Если не устанавливать специально шрифты указанные в ваших css, то получается вот какое не соответствие (см `articles_path`):

---

![screenshot from 2014-09-15 14 13 45](https://cloud.githubusercontent.com/assets/1256298/4270380/6ca8c678-3cca-11e4-937d-26523477977f.png)

---

После того, как я специально установил Menlo, Monaco — стало ок, но ведь этих шрифтов нет по умолчанию в Linux или Windows (не знаю как там в Mac OS). Вам не кажется, что в определении семейства шрифтов следует использовать хотябы один дефолтный шрифт для отображения кода? Типа, если нет всяких там Menlo, Monaco и т.п. отображаем какой нибудь относительно стандартный шрифт (лучше несколько для разных операционок, а не только виндовый `Courier New`).

С уважением

**Comment by khusnetdinov** [comment]
Line-height не задан со шрифтом, которой определяет кусок.

**Comment by Mik-die** [comment]
@khusnetdinov Марат, сможешь пофиксить?

**Comment by khusnetdinov** [comment]
Да, сделаю

**Comment by khusnetdinov** [comment]
Вопрос более не актуален. Проверено на IE + Win.

**Comment by Mik-die** [comment]
У меня тоже все нормально
