### ISSUE TITLE
Доступ к документации по версии 4.2

### ISSUE THREAD

**Issue by danilvoe** [morsbox/rusrails#251]
Будет ли доступна документация по rails 4.2 ? 
Например так же как доступна сейчас документация по 3.2 версии - http://v32.rusrails.ru/

**Comment by Mik-die** [comment]
В планах не было, более того, планирую удалить для версии 3.2

Гайды есть на гитхабе, по тегу https://github.com/morsbox/rusrails/tree/4.2/source

**Comment by danilvoe** [comment]
жаль

**Comment by piton4eg** [comment]
@Mik-die а почему не хочешь?

**Comment by Mik-die** [comment]
@piton4eg да вломы поддерживать)

Можно на хероку поднять попробовать ветку, я могу днс прописать.

**Comment by piton4eg** [comment]
@danilvoe попробуй :)
