### ISSUE TITLE
dockrails:status not working

### ISSUE THREAD

**Issue by vladimirich** [morsbox/rusrails#260]
```
rake aborted!
Git::GitExecuteError: git  clone '--' 'git@github.com:rails/docrails.git' '/Users/nikita/Projects/rusrails/tmp/docrails'  2>&1:Cloning into '/Users/nikita/Projects/rusrails/tmp/docrails'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

So there is no docrails repo nowadays, maybe we should replace it with https://github.com/rails/rails/tree/master/guides . Need help with it?

**Comment by Mik-die** [comment]
No, rails is different repository, with different commit hashes..

docrails repository is private now, don't know why. I asked for access, and they grant me.
