### ISSUE TITLE
Мобильные форматы руководства

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#265]
Есть возможность сгенерировать rusrails в kindle формате в автоматическом режиме, как это происходит на [edge] guides?

**Comment by Mik-die** [comment]
Нет, но если желание, можно реализовать. По идее, можно просто код позаимствовать из rails, переводы на rusrails хранятся в том же формате.

**Comment by diproart** [comment]
Небольшой эксперимент с Gitbook - [RusRails Book](https://www.gitbook.com/book/diproart/rusrails/details). 

Есть возможность скачать как [PDF](https://www.gitbook.com/download/pdf/book/diproart/rusrails), Mobi, [ePub](https://www.gitbook.com/download/epub/book/diproart/rusrails).

Пока просто эксперимент. Всё "как есть", только небольшие изменения для устранения ошибок генератора gitbook.

**Comment by ydakuka** [comment]
Это не то совсем, поддерживать актуальность еще и на гитбуке — дополнительная трата времени.
Имелось в виду, что гайды будут автоматически генерироваться в mobi.

**Comment by diproart** [comment]
Книга генерируется из `/source/*`, редактировать нужно только меню, при изменении структуры, да и его можно в принципе генерировать, это просто список файлов. "Руками" ничего править не нужно, разве что, стили подправить для "INFO:", не более.

Я не согласен, что - "Это не то совсем".  Один в один gitbook, только [TOC](https://github.com/rails/rails/blob/master/guides/source/kindle/toc.html.erb) создается скриптом и не более того. И там и там одна логика. Что мешает при сборке делать `gitbook mobi rails-x.x.x.mobi`.

Вот сейчас в оригинале 404 - http://edgeguides.rubyonrails.org/kindle/ruby_on_rails_guides_v5.1.4.mobi.

Я не спорю с вами @ydakuka Оставляю комментарий, только затем, что может кому-то поможет.

**Comment by ydakuka** [comment]
Оригинал без 404: edgeguides.rubyonrails.org./kindle/ruby_on_rails_guides_4c4d092.mobi

**Comment by Mik-die** [comment]
В генерации мобильного формата/пдф есть два сложных момента

- картинки
- перекрестные ссылки

Сгенерить пдф из хтмл - это не сложно, а вот красивый пдф с картинками и ссылками - сложнее :)

**Comment by robert491** [comment]
@diproart, насколько я понял, https://diproart.gitbooks.io/rusrails/content/ берет контент с ветки [md/view-helpers](https://github.com/morsbox/rusrails/tree/md/view-helpers), тогда как rusrails.ru c [master](https://github.com/morsbox/rusrails/tree/master). Можно ли это как-то исправить, чтобы и гитбукс показывал с master?
