### ISSUE TITLE
Путаница с названиями и адресами файлов

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#280]
Встречаются и такое вариант, когда path и file имеют различное написание, и разделитель слов тире.
```
    path:  active-record-query-interface
    file:  active_record_querying.md
```
А бывает, что разделитель нижнее подчеркивание, например:
```
    path:  active_job_basics
    file:  active_job_basics.md
```

**Comment by Mik-die** [comment]
Да, иногда не услеживал и оставлял с подчеркиваниями :)

Желательно, конечно, файлы с подчеркиванием, а урлы с дэшами.

Но как есть, так есть - страницы проиндексированы поисковиками.
