### ISSUE TITLE
Есть ли смысл в добавлении и переводе "Maintenance Policy for Ruby on Rails"

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#281]
Возник вопрос, есть ли смысл в добавлении и переводе: [Политика обслуживания для Ruby on Rails](http://guides.rubyonrails.org/maintenance_policy.html)
На данный момент раздел в файле ревизий (source/index.yml) находится в группе "plan".

**Comment by Mik-die** [comment]
Планировал, да..

**Comment by Mik-die** [comment]
Только "Политика поддержки (версий)"

**Comment by ydakuka** [comment]
Я в понедельник-вторник переведу, время свободное будет.
