### ISSUE TITLE
#315 fixed?

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#316]
[ #315](https://github.com/morsbox/rusrails/pull/315/) был задеплоен? У меня на локалхост этот баг исправлен, а в удаленной версии - нет, хотя более поздние коммиты, вроде, задеплоены.

**Comment by Mik-die** [comment]
наверрное надо сервер перезапустить, бывает иногда..

**Comment by Mik-die** [comment]
сейчас норм?

**Comment by ydakuka** [comment]
@Mik-die да, норм.
