### ISSUE TITLE
OAuth авторизация на сайте

### ISSUE THREAD

**Issue by deadman2000** [morsbox/rusrails#317]
Не нашел, куда написать, поэтому отпишу тут.
Не работает авторизация через Google и Github на [v32.rusrails.r](http://v32.rusrails.ru/)

**Comment by ydakuka** [comment]
v32 - это архивная версия, она больше не обновляется.

**Comment by Mik-die** [comment]
Более того - если вдруг решу хостинг поменять, ее выпилю :) Я уже и забыл, что она есть.
