### ISSUE TITLE
Перечисления это enum или enumerable?

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#323]
http://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-enumerable
https://github.com/morsbox/rusrails/search?utf8=✓&q=перечисления&type=

**Comment by Mik-die** [comment]
enum - в руби нет, это перечисляемый тип

enumerable я переводил как перечисления, да

**Comment by ydakuka** [comment]
enumerable кроме этих двух мест встречается в английском варианте, поэтому спрашиваю как поступить)

**Comment by ydakuka** [comment]
enumerable кроме этих двух мест встречается в английском варианте, поэтому спрашиваю как поступить)
@Mik-die так что, мне заменять все enumerable на перечисления?

**Comment by Mik-die** [comment]
да, давай
