### ISSUE TITLE
Добавить Ruby on Rails doctrine

### ISSUE THREAD

**Issue by dmitriy-strukov** [morsbox/rusrails#325]
Привет всем! Предлагаю добавить Ruby on Rails соглашение на сайт, это очень важная вещь для понимания многих аспекток того как устроен Ruby / Rails и на каких принципах это все работает.

У меня есть цикл статей на Habrahabr:
https://habrahabr.ru/post/327890/
https://habrahabr.ru/post/328942/
https://habrahabr.ru/post/329844/
https://habrahabr.ru/post/330650/

Если утверждаете задачу, то готов приступить к выполению ))

**Comment by dmitriy-strukov** [comment]
@Mik-die посмотрите пожалуйста

**Comment by ydakuka** [comment]
Rusrails - это перевод официальных гайдов, а не сайт с переводом статей.
И сколько таких нужных статей наберется, и все добавлять?
Считаю, что не нужно захламлять "перевод гайдов", ведь хабра хорошо справляется с коллекционированием статей, спасибо им за это.
Но решать @Mik-die

**Comment by Mik-die** [comment]
Я не хотел бы выкладывать что-то больше, чем переводы гайдов. Если помните, лет 7 назад была тема с публикациями/регистрациями/комментами, но это все не нужно оказалось.

Но! Я только за, чтобы выкладывать ссылки на эти статьи. Например, в этом разделе: http://rusrails.ru/getting-started-with-rails#chto-dalshe

И если вдруг ссылок станет много, можно даже отдельную страницу сделать.

**Comment by dmitriy-strukov** [comment]
@Mik-die ок, тогда прикреплю 4 ссылки на перевод соглашения?

**Comment by ydakuka** [comment]
Почему бы не написать мэйнтейнерам rubyonrails.ru (в футере контакты), чтобы они разместили статью целиком по адресу:
rubyonrails.ru/doctrine/
И потом на статью на этот сайте ссылку?

И проверьте еще раз перевод.
https://habrahabr.ru/post/327890/#comment_10202316

**Comment by dmitriy-strukov** [comment]
@ydakuka спасибо так и сделал.
