### ISSUE TITLE
Я в смятении по след. разделу

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#330]
Проверяю следующий раздел и натолкнулся на следующее:
![https://image.ibb.co/dcRcA5/image.png](https://image.ibb.co/dcRcA5/image.png)
Кто врет?

**Comment by Mik-die** [comment]
самое первое подчеркивание врет, остальное правильно :)

**Comment by ydakuka** [comment]
@Mik-die первое в русском варианте?

**Comment by Mik-die** [comment]
ага
