### ISSUE TITLE
Вопрос по разделу form helpers

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#332]
В след. разделе небольшая путаница:
http://rusrails.ru/rails-form-helpers
http://guides.rubyonrails.org/form_helpers.html

Есть англ. слово: option
И "Select options" переведено как "список варианта выбора".
Где в этой статье использовать перевод как "вариант/вариант выбора", а где как "опций"?

А вообще, это пока самый лучший перевод, что вообще есть/был на rusrails, что я встречал.

Можешь по пунктам расписать, что где на что исправить?

**Comment by Mik-die** [comment]
Тут все просто

- если речь идет про теги - `<option>` - это вариант выбора
- если речь идет про ключевые аргументы в методах руби - это опции.

**Comment by ydakuka** [comment]
Это правильно.
Когда что использует тоже понимаю.
Немного неправильно вопрос сформулировал.
Пересечений между <option> и опциями никаких нет? Ну чтобы в тексте использовалось и первое, и второе одновременно.

**Comment by Mik-die** [comment]
скорее всего нет

**Comment by ydakuka** [comment]
Ладн, я исправлю, если будут замечания - скажешь.
