### ISSUE TITLE
При клике по ссылке "Удалено" в каждом из подразделов переносит на один и тот же path #udaleno

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#337]
В guides это решено добавлением подраздела в качестве префикста, например:
для Action Mailer будет #action_mailer_udaleno

**Comment by Mik-die** [comment]
Можно починить в лоб, добавив правильный хэштег в скобках, т.е;

```
### (removed-1) Удалено
```

**Comment by ydakuka** [comment]
Ну это я знаю, видел в других разделах так и сделано. А автоматом, чтобы ставилось?

**Comment by Mik-die** [comment]
Это нужно чинить тут: https://github.com/morsbox/rusrails/blob/master/lib/renderers/markdown.rb#L45

Сделать сет, туда запоминать уже сгенеренные хэштеги, если встретили дубликат, добавить индекс
