### ISSUE TITLE
Перевод комментариев в action controller overview

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#341]
Может быть это тоже следует перевести?
В конфигах могут быть удалены/смещены другой командой комментарии, например, и другие причины.
![http://image.ibb.co/hKB2ua/image.png](http://image.ibb.co/hKB2ua/image.png)

**Comment by Mik-die** [comment]
не думаю, они относятся не к гайдам, а к самой рельсе (шаблону), а там все на английском

**Comment by ydakuka** [comment]
Я знаю, но так будет понятнее, что делает каждая команда, если ее раскомментировать.
