### ISSUE TITLE
Перевод namespace и scope?

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#346]
Что-то одно "пространство имен", скорее всего, это - namespace.
А что-то scope...
Предлагаю scope - "область видимости".

**Comment by Mik-die** [comment]
Да, давай, только без энтузиазма :) Там где они рядом встречаются. Иногда лучше по смыслу смотреть.

**Comment by ydakuka** [comment]
Хорошо. Заметил, что встречается только в одной гайде routing,  мб ошибаюсь, и где-нибудь еще.

Мне не нужно проверять все гайды?)

**Comment by Mik-die** [comment]
Чтобы прямо в коде встречались - это только в роутинге только. Думаю, что в остальных гайдах если и встречаются, то в качестве синонимов.
