### ISSUE TITLE
generate и create

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#349]
Еще предлагаю пересмотреть перевод generate и create. Почти везде в гайдах переведено и то, и другое как создают.

А предлагаю:
generate - генерируют
create - создают

**Comment by Mik-die** [comment]
Да, если не трудно все пересмотреть :) Можно перевод разделить. Нашел доступное объяснение, чем слова отличаются https://ell.stackexchange.com/a/76988

**Comment by ydakuka** [comment]
Может быть и трудно, но я никуда не спешу. За месяц-два сделаю :), хотя думаю быстрее, по настроению.
