### ISSUE TITLE
"by default" и "default"

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#351]
Почти везде перепутан перевод этих значений:
generator by default - генератор по умолчанию
default generator - дефолтный генератор

Обычно в тексте встречается только первый вариант.

Потом исправлю.

**Comment by Mik-die** [comment]
не вижу разницы :)

**Comment by ydakuka** [comment]
Плохо описал проблему, объясню на примере.
"While the default routes and helpers generated by resources :articles ..."
В переводе: "Хотя маршруты и помощники по умолчанию, генерируемые ресурсами: статьи...", хотя дефолтные маршруты и хелперы.

"By default, Rails creates routes for the seven default actions"
"По умолчанию Rails создает маршруты для семи экшнов по умолчанию", хотя
"По умолчанию, Rails создает маршруты для семи дефолтных экшнов"

**Comment by ydakuka** [comment]
Почти везде нормально :/
