### ISSUE TITLE
asset и resource

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#352]
Встречал в тексте что оба этих слова переведены как "ресурсы".

**Comment by Mik-die** [comment]
Это самая тяжелая проблема перевода, с которой я встретился при работе с гайдами.. Можно, конечно, сдаться и переводить как "ассеты", но может все же есть термин правильный?

**Comment by ydakuka** [comment]
Я в гайдах находил перевод asset как ассеты и ресурсы.
Посмотрю в рельс-книгах, может быть там что-нибудь интересное найдется.
Но мне вариант ассет нравится больше, чем ресурс.

**Comment by Mik-die** [comment]
ну давай ассет примем как единственно верный. Просто этот термин довольно поздно в рельсе появился, в 3.0 еще не было ни pipeline, ни папки assets

**Comment by ydakuka** [comment]
Роман Снитко в своей книге использует "ассеты".

В "The Ruby Way"
Механизм автоматизации этого процесса включен в Rails под названием конвейера активов (asset pipeline).

**Comment by ydakuka** [comment]
Хотя вот здесь используется перевод "активы":
railstutorial.ru/ <-- то же непрофессиональный перевод.
Гибкая разработка веб-приложений в среде Rails (2008) <-- в последующих изданиях они стали избегать перевода asset, вместо этого они используют в каталоге `app/assets`, например.

**Comment by Mik-die** [comment]
активы - это из бизнес терминологии, для нас не очень подходит

Давай "ассеты" переводить, будет калька с английского, переводим же уже "вьюхи" и "экшны"

**Comment by ydakuka** [comment]
Я тоже так думаю, тем более используется в обиходе "ассеты".
