### ISSUE TITLE
"Перевод" или "оригинал" комментариев кода

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#355]
Один раздел, но в одном случае переведено (слово исправлю :) ), а в другом - нет.

http://rusrails.ru/upgrading-ruby-on-rails#gemfile

http://rusrails.ru/upgrading-ruby-on-rails#uroven-loga-v-production

В других разделах то же самое.

**Comment by ydakuka** [comment]
Ты, вроде, говорил, что такие не переводить.

Может быть мне проверить и обратно вернуть на исходный вариант переведенное?

**Comment by Mik-die** [comment]
Я придерживался логики: если коммент генерируется рельсой - оставляется, если это пояснение к примеру - переводится. Но, в принципе, ничего страшного, если их все переводить.

**Comment by ydakuka** [comment]
Закрою это до лучших времен.
Пока есть более чем важным заняться.
Когда других забот не останется, а время останется (может быть :) ), тогда вернусь к этому.
