### ISSUE TITLE
parent / children / child

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#359]
?

**Comment by ydakuka** [comment]
И еще, слово "predicate" переведено как "условие", хотя, думаю, правильнее будет предикат.
Условие - это condition. Как считаешь?

**Comment by Mik-die** [comment]
Да, predicate - это не условие, неверно переведено значит. предикат норм

parent/child нужно в контексте смотреть, если абстрактно - это родительский/дочерний элемент(ы)

**Comment by ydakuka** [comment]
Да, в контексте.

Предлагаю:
Parent - родитель. 
child - потомок
children - дочерний.


А то я видел (И другие варианты, не помню точно (: ):
Parent - родитель, предок, 
child - ребенок, дитя, потомок
children - дочерний.

**Comment by Mik-die** [comment]
потомок для child - это некорректный будет перевод, т.к. child - это всего лишь первый потомок.

То есть A -> B -> C. Тут у A only child is B, but потомоки это B & C

потомок - это descendant, к тому же

**Comment by ydakuka** [comment]
Могу предложить так: я найду и исправлю все что есть, а там уже если не согласен будешь, то скажешь что исправить.
