### ISSUE TITLE
перевод "custom"

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#362]
in custom Ajax calls - пользовательские или произвольные аякс вызовы?

Либо как-нибудь по-другому?

**Comment by Mik-die** [comment]
пользовательские -  опасное слово, двусмысленное :)

я предпочитаю "произвольные"

**Comment by ydakuka** [comment]
Погуглил перевод, как насчет таким вариантов?
собственный
индивидуальный

Просто лично мне не понятно, что означает выражение "произвольные аякс вызовы".

**Comment by Mik-die** [comment]
собственный - вроде тоже норм, передает смысл
