### ISSUE TITLE
test case / test suite

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#364]
_test case_ ([тестовый случай](https://ru.wikipedia.org/wiki/%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82_%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)) и _test suite_ (тестовый набор).

**Comment by Mik-die** [comment]
мм, в чем вопрос? Да, я вроде так и переводил

**Comment by ydakuka** [comment]
Это не вопрос, просто я нашел неточности в тексте и чтобы не забыть проверить и исправить, где не так.

Текущий PR и так большой, что сложно было проверять, не хотел его делать еще больше.
