### ISSUE TITLE
перевод "single"

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#366]
> For every **single** method defined as a core extension this guide has a note that says where such a method is defined.

>Для каждого **отдельного** метода, определенного как расширение ядра, в этом руководстве имеется заметка, сообщающая, где такой метод определяется.

Единственного / единого / отдельного?

Дословный перевод "единого"

**Comment by Mik-die** [comment]
тут по смыслу правильный перевод сейчас. Устойчивое выражение
