### ISSUE TITLE
перевод "mailer"

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#368]
Сейчас везде на rusrails переводится как "рассыльщик". Почему не мейлер или мэйлер?
Если не ошибаюсь, то второй вариант больше прижился.

**Comment by Mik-die** [comment]
Не знаю, как то начал так переводить :) Вроде смысл передает

**Comment by ydakuka** [comment]
Может заменить на мэйлер?

**Comment by ydakuka** [comment]
Просто в речи истощения мэйлер, а не рассыльщик.

**Comment by ydakuka** [comment]
Просто в речи используется мэйлер.

**Comment by ydakuka** [comment]
@Mik-die ?

**Comment by Mik-die** [comment]
А в каких книгах встречается? Я просто не сторонник жаргонизмов, если есть более-менее нормальный перевод

**Comment by ydakuka** [comment]
Проверил. Плохая идея в этом топике.

В книгах про рельсы перевод слова mailer избегают, перефразируя предложения.
Затем хотел найти в других ЯП (как делал это недавно), но оказалось, что гугл нашел не "мейлер", а "mailer" в англ. версиях.
