### ISSUE TITLE
Вопросы по переводу

### ISSUE THREAD

**Issue by ydakuka** [morsbox/rusrails#369]
Здесь я буду размещать слова, по которым возникли вопросы по переводу.

**Comment by ydakuka** [comment]
parent / child (children) == родительский / дочерний (потомок?)
predicate == предикат.
custom == собственный
test case / test suite == тестовый случай / тестовый набор.
eval / evaluate == выполнять
string / line == строка / строчка


#359 #362 #364 #365 #367

**Comment by ydakuka** [comment]
- [x] task и job 
 - [ ] parent / child (children) == родительский / дочерний (потомок?)
 - [ ] predicate == предикат.
 - [ ] custom == собственный
 - [ ] test case / test suite == тестовый случай / тестовый набор.
 - [ ] eval / evaluate == выполнять
 - [ ] string / line == строка / строчка
 - [ ] исправить в `asset_pipeline.md` <-- "веб сервер".

#359 #362 #364 #365 #367

**Comment by ydakuka** [comment]
@Mik-die, мне по прежнему не особо нравится "custom == собственный" м.б. использовать кастомный или https://www.lingvolive.com/ru-ru/community/posts/39319, м?

Кастомный очень часто встречается в речи) и это понятный жаргонизм, как считаешь?

**Comment by Mik-die** [comment]
Я воспринимаю слово кастомный как настраиваемый, это не всегда подходит по контексту. В общем, слово custom нельзя однозначно перевести, очень важен контекст

**Comment by ydakuka** [comment]
как все сложно :/

**Comment by ydakuka** [comment]
@Mik-die 
Я везде проверяю-изменяю section как разделы (кое-где изменил ранее на секции, что неправильно, исправляю).

Еще вопрос, вот допустим есть [текст](http://edgeguides.rubyonrails.org/layouts_and_rendering.html#asset-tag-helpers):

> You can use these tags in layouts or other views, although the auto_discovery_link_tag, javascript_include_tag, and stylesheet_link_tag, are most commonly used in the **<head> section** of a layout.

И вот **<head> section** - это область или секция?

**Comment by Mik-die** [comment]
В layout-ах это тоже переводится как раздел http://htmlbook.ru/html/section

**Comment by ydakuka** [comment]
С разделом в html разобрались, а что делать  с `сconfig/database.yml`?

**Comment by Mik-die** [comment]
Да пускай и там будут разделы

**Comment by ydakuka** [comment]
@Mik-die как на счет того, чтобы сделать следующее:
экшн/экшне => экшен/экшене
продакшн/продакшне => продакшен/продакшене
и другие похожие слова с "кшн"
?

**Comment by Mik-die** [comment]
> Показаны результаты по запросу продакшн
> Искать вместо этого продакшен

**Comment by ydakuka** [comment]
Понял, просто "экшне" слух режет.

**Comment by ydakuka** [comment]
Как правильно, "пул реквест" или "пул-реквест"? Почему через дефис используется, откуда он вообще взялся, понять не могу.

**Comment by ydakuka** [comment]
Вопрос, как перевести "upgrade и update" НЕ в контексте экшнов?

**Comment by ydakuka** [comment]
Попробовал перевод custom поисправлять, слишком сложно, думать надо.
Например,

> Некоторые типы, такие как decimal, принимают произвольные опции.
Some types such as decimal accept custom options.

> Added an `:authenticity_token` option to `form_tag` for custom handling or to omit the token by passing `:authenticity_token => false`.
Добавлена опция `:authenticity_token` к `form_tag` для ручного управления, или для отмены, если передать `:authenticity_token => false`.

т.е. если заменить на собственные, то намного непонятнее становится.

**Comment by ydakuka** [comment]
eval/evaluate/evaluation - выполнения/вычисление?

https://ru.wikipedia.org/wiki/Ленивые_вычисления

**Comment by Mik-die** [comment]
вычисление

**Comment by Mik-die** [comment]
пул-реквест - по правилам русского, если два существительных образуют одно слово, пишутся через дефис (сапоги-скороходы, жар-птица и тп)

**Comment by Mik-die** [comment]
Согласен с обновление и апгрейд

**Comment by ydakuka** [comment]
Встречается в гайдах такой перевод:
engine-ы, engine-е.
Мб поудалять эти склонение?

**Comment by Mik-die** [comment]
Если склонение явно понятно из контекста - то лучше да, удалить. Я старался добавлять это окончание, где была неоднозначность

**Comment by ydakuka** [comment]
@Mik-die как перевести следующее:

1) remove / delete / destroy === убрать (изъять?) / удалить / уничтожить
2) Credentials == полномочия / учетные данные ???
3) "regular" == переведено местами как "надлежащие"
4) output - результат / вывод / ответ?
5) modify - видоизменить?? // вносить (внести) изменение // модифицирует (менее всего нравится)

**Comment by Mik-die** [comment]
remove / delete / destroy === убрать / удалить / уничтожить
Credentials == учетные данные
"regular" == от контеста зависит (где-то регулярный, где-то обычный)
output - мм, не задумывался :) Результат вывода? Вывод результата?
modify - вносить изменение / изменять

**Comment by ydakuka** [comment]
@Mik-die 
Как насчет такого?
feature/bug - фича/баг вместо особенность/ошибка

Особенность - это непонятно вообще о чем.

**Comment by ydakuka** [comment]
Я уже как-то поднимал вопрос по поводу перевода слова "serve", и почитав другие руководства - правильнее будет так:

serve - служить (служат)

serving - обслуживать

**Comment by Mik-die** [comment]
> The Institute of Electrical and Electronics Engineers defines the term feature in IEEE 829 as "A distinguishing characteristic of a software item (e.g., performance, portability, or functionality)."

то есть feature - это отличительная особенность.

Мне поначалу было по-приколу вставлять жаргонизмы (вьюхи, экшны и т.п.) - но сейчас это уже не кажется хорошей идеей. Взрослею, наверное :)

Bug - https://ru.wikipedia.org/wiki/Программная_ошибка

> In computing, the term "issue" is a unit of work to accomplish an improvement in a system. An issue could be a bug, a requested feature, task, missing documentation, and so forth.

Даже не знаю, какой термин подобрать, "проблема" достаточно точно описывает.

Цитаты их английской вики

**Comment by ydakuka** [comment]
Ок, пока только фича как отличительная особенность вызывает отторжение.

Ну, а вьюха — это святое, даже не предложил бы заменить.

**Comment by ydakuka** [comment]
@Mik-die какой перевод выражений:
secrets (это про config/) - предлагаю секреты, местами переведено как секретные данные
sensitive information - чувствительная информация [link](https://dic.academic.ru/dic.nsf/fin_enc/31656)? Информация с ограниченным доступом ? Сейчас это "деликатная информация"

**Comment by Mik-die** [comment]
Если вики верить https://en.wikipedia.org/wiki/Information_sensitivity => https://ru.wikipedia.org/wiki/Секретная_информация

Про secrets - может перевести производно от слова тайна? Опять если верить вики https://en.wikipedia.org/wiki/Secret_(disambiguation) => Top-secret information, a level of classified information => https://en.wikipedia.org/wiki/Classified_information => https://ru.wikipedia.org/wiki/Государственная_тайна

**Comment by ydakuka** [comment]
@Mik-die я видел про "секретную информацию" в вики, но сразу непонятно о какой именно идет речь. Значение с config/secrets путается, мне кажется.

Нет, "тайна" - это вообще не понятно о чем речь) Мб все-таки секреты?

**Comment by ydakuka** [comment]
И еще, bug fix - это багфикс или исправление программной ошибки?

**Comment by Mik-die** [comment]
ну ок, давай дословно тогда

**Comment by ydakuka** [comment]
Ок, так какой перевод sensitive выбрать?

**Comment by Mik-die** [comment]
чувствительная

**Comment by reabiliti** [comment]
Добрый день,
нашел грамматическую ошибку в переводе:
https://monosnap.com/file/WLdAzo1GxTnncQlmT3HGHQ17o6PBaS
не знаю, куда написать, решил сюда.
