### ISSUE TITLE
Починить spellcheck

### ISSUE THREAD

**Issue by mikdiet** [morsbox/rusrails#441]
Мы проверяем орфографию с помощью `npm run yaspeller`

Хотя исключения хранятся в `.yaspeller.json` - они не всегда подхватываются; несколько примеров:

```
✗ /home/circleci/repo/source/4_2_release_notes.md 668 ms
-----
Typos: 1
1. к ассету (453:336, suggest: кассету)
-----

✗ /home/circleci/repo/source/action_controller_overview.md 1153 ms
-----
Typos: 1
1. по токену (count: 2, suggest: потоке ну)
-----
```

Нужно разобраться, в чем проблема, и починить.

**Comment by pecheneg2015** [comment]
Эта проблема связана с тем, что используется "контекст". Т.е чтобы добиться ожидаемого поведения необходимо рассматривать `к ассету`  как 2 отдельных слова, а не словосочетание.
Для этого можно вызвать  `yaspeller` с параметром `--by-words` (можно указать в `.yaspeller.json`).
