### ISSUE TITLE
При выделении текста в блоке кода происходит выделение лишних фрагментов

### ISSUE THREAD

**Issue by mechnicov** [morsbox/rusrails#454]
При попытке выделить код выделяется нижелеажщий заголовок:

![](https://i.imgur.com/4YUdmWj.png)

Как воспроизвести:

Перейти [по ссылке](http://rusrails.ru/active-record-basics#udalenie)

Начать выделять текст в блоке сверху вниз

**Comment by mikdiet** [comment]
Спасибо за фикс!
